### ISSUE TITLE
Given groups=1, weight of size [320, 4, 3, 3], expected input[8, 8, 96, 57] to have 4 channels, but got 8 channels instead

### ISSUE THREAD

**Issue by kubilaykilinc** [huagetai/ComfyUI-Gaffer#1]
I tried example workflows. I am getting this error

Given groups=1, weight of size [320, 4, 3, 3], expected input[8, 8, 96, 57] to have 4 channels, but got 8 channels instead

**Comment by huagetai** [comment]
which one? It is necessary to ensure that the width and height of the foreground image and Lighting Preference  image are consistent.

**Comment by Fox-pix** [comment]
Error occurred when executing ICLightModelLoader:

'time_embedding.linear_1.weight'

**Comment by kubilaykilinc** [comment]
I tried now with simple text to image example workflow. And i've got same error. I have different IC Light custom node. I did not get this error with same image.

**Comment by huagetai** [comment]
It used to depend on ComfyUI-layerdiffusion, but now it no longer depends on it. Please update.
